import type { Metadata } from 'next';
import './globals.css';
import { AuthProvider } from '@/Context/AuthContext';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// Root layout will be shared through all of the different pages/routes
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // Html and Body tags are required in the layout
    <html lang="en">
      <body className="bg-primary text-secondary w-screen h-screen">
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
